# values.yaml for Grafana Helm Chart

# Enable persistence for Grafana
persistence:
  enabled: true
service:
  type: NodePort
  nodePort: 30744

# Set a custom admin password (optional)
adminPassword: "admin"

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: "http://161.35.216.161:31865"  # Prometheus URL
        isDefault: true
        editable: true
